// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqzjhvcxuyydxumkvdhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxempodmN4dXl5ZHh1bWt2ZGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNjIyNTIsImV4cCI6MjA1NDkzODI1Mn0.ZvjJHR0LOuT0i0oWFAVS_SWlDylOF6VehCNp-YHo8E8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);